# Generated by Django 3.0.5 on 2020-09-25 08:34

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='厂家名称')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='厂家地址')),
                ('status', models.BooleanField(default=True, verbose_name='当前状态')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufactor_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufactor_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '生产厂家基本信息',
                'verbose_name_plural': '生产厂家基本信息',
            },
            bases=(models.Model, common.models.DictMixin),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='传感器名称')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='传感器型号')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='传感器唯一编号')),
                ('status', models.BooleanField(default=True, verbose_name='当前状态')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensor_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('manufactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_manufactor', to='valve.Manufactor', verbose_name='生产厂家')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensor_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '传感器设备',
                'verbose_name_plural': '传感器设备',
            },
            bases=(models.Model, common.models.DictMixin),
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('valtage', models.CharField(blank=True, max_length=255, null=True, verbose_name='电压测量量')),
                ('status', models.BooleanField(default=True, verbose_name='当前状态')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valtage_senor', to='valve.Sensor', verbose_name='所属传感器')),
            ],
            options={
                'verbose_name': '电压测量记录',
                'verbose_name_plural': '电压测量记录',
            },
            bases=(models.Model, common.models.DictMixin),
        ),
        migrations.CreateModel(
            name='WarnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warn_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警信息')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warn_senor', to='valve.Sensor', verbose_name='所属传感器')),
            ],
            options={
                'verbose_name': '告警信息记录',
                'verbose_name_plural': '告警信息记录',
            },
            bases=(models.Model, common.models.DictMixin),
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
