# Generated by Django 3.0.5 on 2020-09-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='wechat_user',
        ),
        migrations.DeleteModel(
            name='Operational',
        ),
        migrations.DeleteModel(
            name='WechatUser',
        ),
    ]
